id: recon_smb_enum
name: SMB Enumerating
category: 1) Reconnaissance and Discovery
subcategory: 1.2 Port, service, OS, and vulnerability scanning
description: Enumeration of SMB share directories and vulnerabilities.
image: attack-smb-enumerating:latest
container_name: attack-smb-enumerating
max_runtime_s: 10
target_services:
- target IP service
target_mapping:
  target: target_ip
mitre:
- https://attack.mitre.org/tactics/TA0007/
- https://attack.mitre.org/tactics/TA0043/
- https://attack.mitre.org/techniques/T1595/002/
- https://attack.mitre.org/techniques/T1135/
params:
- key: target_ip
  label: Target IP address or FQDN
  kind: ip
  placeholder: __HOST_IP__
