id: exf_icmp_tunnel
name: ICMP Tunnel
category: 5) Exfiltration and Tunneling
subcategory: 5.1 Exfiltration and Tunneling
description: TCP port 22 (SSH) tunnel over ICMP (pings).
image: attack-icmp-tunnel:latest
container_name: attack-icmp-tunnel
max_runtime_s: 10
target_services:
- ssh-server
target_mapping:
  target: target_ip
  port: target_port
mitre:
- https://attack.mitre.org/tactics/TA0011/
- https://attack.mitre.org/techniques/T1090/
- https://attack.mitre.org/techniques/T1095/
- https://attack.mitre.org/techniques/T1572/
params:
- key: target_ip
  label: Target IP address or FQDN
  kind: ip
  placeholder: __HOST_IP__
- key: target_port
  label: Target port
  kind: port
  placeholder: '2222'
  default: 2222
